type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  bio: String
  contactEmail: String
  linkedinUrl: String
  githubUrl: String
  websiteUrl: String
}

type Portfolio @table {
  user: User!
  name: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type Project @table {
  portfolio: Portfolio!
  title: String!
  description: String!
  position: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  category: String
  liveUrl: String
  repositoryUrl: String
}

type ProjectMedia @table {
  project: Project!
  mediaUrl: String!
  mediaType: String!
  position: Int!
  caption: String
}

type Skill @table {
  user: User!
  name: String!
  level: String
}